// <auto-generated />
namespace VideoLibrary.BusinessEntities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VirtualActorInMovie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VirtualActorInMovie));
        
        string IMigrationMetadata.Id
        {
            get { return "201801151257270_Virtual Actor In Movie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
